services:
  barracuda-IMU-node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: barracuda-IMU-node
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    networks:
      - ros
